//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PAPELETAEntities : DbContext
    {
        public PAPELETAEntities()
            : base("name=PAPELETAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_COLOR> TB_COLOR { get; set; }
        public virtual DbSet<TB_INFRACCION> TB_INFRACCION { get; set; }
        public virtual DbSet<TB_INFRACTOR> TB_INFRACTOR { get; set; }
        public virtual DbSet<TB_MARCA> TB_MARCA { get; set; }
        public virtual DbSet<TB_PAPELETA> TB_PAPELETA { get; set; }
        public virtual DbSet<TB_POLICIA> TB_POLICIA { get; set; }
        public virtual DbSet<TB_RANGO> TB_RANGO { get; set; }
        public virtual DbSet<TB_TIPO_VEHICULO> TB_TIPO_VEHICULO { get; set; }
        public virtual DbSet<TB_UBIGEO> TB_UBIGEO { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<TB_VEHICULO> TB_VEHICULO { get; set; }
        public virtual DbSet<VW_INFRACCION> VW_INFRACCION { get; set; }
        public virtual DbSet<VW_INFRACTOR> VW_INFRACTOR { get; set; }
        public virtual DbSet<VW_PAPELETA> VW_PAPELETA { get; set; }
        public virtual DbSet<VW_POLICIA> VW_POLICIA { get; set; }
        public virtual DbSet<VW_UBIGEO> VW_UBIGEO { get; set; }
        public virtual DbSet<VW_VEHICULO> VW_VEHICULO { get; set; }
        public virtual DbSet<VW_VISTAMULTAS> VW_VISTAMULTAS { get; set; }
    
        public virtual int SP_ACTUALIZAR_INFRACCION(string cOD_INFRACCION, string dESCRIPCION, string cALIFICACION, Nullable<int> pUNTOS, Nullable<decimal> uIT, string eSTADO, string mEDIDA)
        {
            var cOD_INFRACCIONParameter = cOD_INFRACCION != null ?
                new ObjectParameter("COD_INFRACCION", cOD_INFRACCION) :
                new ObjectParameter("COD_INFRACCION", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var cALIFICACIONParameter = cALIFICACION != null ?
                new ObjectParameter("CALIFICACION", cALIFICACION) :
                new ObjectParameter("CALIFICACION", typeof(string));
    
            var pUNTOSParameter = pUNTOS.HasValue ?
                new ObjectParameter("PUNTOS", pUNTOS) :
                new ObjectParameter("PUNTOS", typeof(int));
    
            var uITParameter = uIT.HasValue ?
                new ObjectParameter("UIT", uIT) :
                new ObjectParameter("UIT", typeof(decimal));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var mEDIDAParameter = mEDIDA != null ?
                new ObjectParameter("MEDIDA", mEDIDA) :
                new ObjectParameter("MEDIDA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_INFRACCION", cOD_INFRACCIONParameter, dESCRIPCIONParameter, cALIFICACIONParameter, pUNTOSParameter, uITParameter, eSTADOParameter, mEDIDAParameter);
        }
    
        public virtual int SP_ACTUALIZAR_INFRACTOR(string cOD_INFRACTOR, string dNI, string aPE_PATERNO, string aPE_MATERNO, string nOMBRES, string cORREO, string dIRECCION, string cOD_UBIGEO, string sEXO, Nullable<System.DateTime> fEC_NACIMIENTO, byte[] fOTO, string nRO_BREVETE, string tIPO_BREVETE, string eSTADO, string uSU_ULT_MODIFICACION)
        {
            var cOD_INFRACTORParameter = cOD_INFRACTOR != null ?
                new ObjectParameter("COD_INFRACTOR", cOD_INFRACTOR) :
                new ObjectParameter("COD_INFRACTOR", typeof(string));
    
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var aPE_PATERNOParameter = aPE_PATERNO != null ?
                new ObjectParameter("APE_PATERNO", aPE_PATERNO) :
                new ObjectParameter("APE_PATERNO", typeof(string));
    
            var aPE_MATERNOParameter = aPE_MATERNO != null ?
                new ObjectParameter("APE_MATERNO", aPE_MATERNO) :
                new ObjectParameter("APE_MATERNO", typeof(string));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var cOD_UBIGEOParameter = cOD_UBIGEO != null ?
                new ObjectParameter("COD_UBIGEO", cOD_UBIGEO) :
                new ObjectParameter("COD_UBIGEO", typeof(string));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var fEC_NACIMIENTOParameter = fEC_NACIMIENTO.HasValue ?
                new ObjectParameter("FEC_NACIMIENTO", fEC_NACIMIENTO) :
                new ObjectParameter("FEC_NACIMIENTO", typeof(System.DateTime));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            var nRO_BREVETEParameter = nRO_BREVETE != null ?
                new ObjectParameter("NRO_BREVETE", nRO_BREVETE) :
                new ObjectParameter("NRO_BREVETE", typeof(string));
    
            var tIPO_BREVETEParameter = tIPO_BREVETE != null ?
                new ObjectParameter("TIPO_BREVETE", tIPO_BREVETE) :
                new ObjectParameter("TIPO_BREVETE", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var uSU_ULT_MODIFICACIONParameter = uSU_ULT_MODIFICACION != null ?
                new ObjectParameter("USU_ULT_MODIFICACION", uSU_ULT_MODIFICACION) :
                new ObjectParameter("USU_ULT_MODIFICACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_INFRACTOR", cOD_INFRACTORParameter, dNIParameter, aPE_PATERNOParameter, aPE_MATERNOParameter, nOMBRESParameter, cORREOParameter, dIRECCIONParameter, cOD_UBIGEOParameter, sEXOParameter, fEC_NACIMIENTOParameter, fOTOParameter, nRO_BREVETEParameter, tIPO_BREVETEParameter, eSTADOParameter, uSU_ULT_MODIFICACIONParameter);
        }
    
        public virtual int SP_ACTUALIZAR_PAPELETA(string cOD_PAPELETA, string lUGAR, string dESCRIPCION, string oBSERVACIONES)
        {
            var cOD_PAPELETAParameter = cOD_PAPELETA != null ?
                new ObjectParameter("COD_PAPELETA", cOD_PAPELETA) :
                new ObjectParameter("COD_PAPELETA", typeof(string));
    
            var lUGARParameter = lUGAR != null ?
                new ObjectParameter("LUGAR", lUGAR) :
                new ObjectParameter("LUGAR", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var oBSERVACIONESParameter = oBSERVACIONES != null ?
                new ObjectParameter("OBSERVACIONES", oBSERVACIONES) :
                new ObjectParameter("OBSERVACIONES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_PAPELETA", cOD_PAPELETAParameter, lUGARParameter, dESCRIPCIONParameter, oBSERVACIONESParameter);
        }
    
        public virtual int SP_ACTUALIZAR_POLICIA(string cOD_POLICIA, string nOMBRE, string pATERNO, string mATERNO, string dNI, string cOD_UBIGEO, Nullable<int> cOD_RANGO, string sEXO, Nullable<System.DateTime> fECHANACIMIENTO, string eSTADO, byte[] fOTO, string uSU_ULT_MODIFICACION)
        {
            var cOD_POLICIAParameter = cOD_POLICIA != null ?
                new ObjectParameter("COD_POLICIA", cOD_POLICIA) :
                new ObjectParameter("COD_POLICIA", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var pATERNOParameter = pATERNO != null ?
                new ObjectParameter("PATERNO", pATERNO) :
                new ObjectParameter("PATERNO", typeof(string));
    
            var mATERNOParameter = mATERNO != null ?
                new ObjectParameter("MATERNO", mATERNO) :
                new ObjectParameter("MATERNO", typeof(string));
    
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var cOD_UBIGEOParameter = cOD_UBIGEO != null ?
                new ObjectParameter("COD_UBIGEO", cOD_UBIGEO) :
                new ObjectParameter("COD_UBIGEO", typeof(string));
    
            var cOD_RANGOParameter = cOD_RANGO.HasValue ?
                new ObjectParameter("COD_RANGO", cOD_RANGO) :
                new ObjectParameter("COD_RANGO", typeof(int));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var fECHANACIMIENTOParameter = fECHANACIMIENTO.HasValue ?
                new ObjectParameter("FECHANACIMIENTO", fECHANACIMIENTO) :
                new ObjectParameter("FECHANACIMIENTO", typeof(System.DateTime));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            var uSU_ULT_MODIFICACIONParameter = uSU_ULT_MODIFICACION != null ?
                new ObjectParameter("USU_ULT_MODIFICACION", uSU_ULT_MODIFICACION) :
                new ObjectParameter("USU_ULT_MODIFICACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_POLICIA", cOD_POLICIAParameter, nOMBREParameter, pATERNOParameter, mATERNOParameter, dNIParameter, cOD_UBIGEOParameter, cOD_RANGOParameter, sEXOParameter, fECHANACIMIENTOParameter, eSTADOParameter, fOTOParameter, uSU_ULT_MODIFICACIONParameter);
        }
    
        public virtual int SP_ACTUALIZAR_VEHICULO(string cOD_VEHICULO, string cOD_INFRACTOR, string cOD_MARCA, string cOD_COLOR, string tIPO_VEHICULO, Nullable<int> aNIO_FABRICACION, string nRO_MOTOR, string eSTADO, byte[] fOTO, string uSU_ULT_MODIFICACION)
        {
            var cOD_VEHICULOParameter = cOD_VEHICULO != null ?
                new ObjectParameter("COD_VEHICULO", cOD_VEHICULO) :
                new ObjectParameter("COD_VEHICULO", typeof(string));
    
            var cOD_INFRACTORParameter = cOD_INFRACTOR != null ?
                new ObjectParameter("COD_INFRACTOR", cOD_INFRACTOR) :
                new ObjectParameter("COD_INFRACTOR", typeof(string));
    
            var cOD_MARCAParameter = cOD_MARCA != null ?
                new ObjectParameter("COD_MARCA", cOD_MARCA) :
                new ObjectParameter("COD_MARCA", typeof(string));
    
            var cOD_COLORParameter = cOD_COLOR != null ?
                new ObjectParameter("COD_COLOR", cOD_COLOR) :
                new ObjectParameter("COD_COLOR", typeof(string));
    
            var tIPO_VEHICULOParameter = tIPO_VEHICULO != null ?
                new ObjectParameter("TIPO_VEHICULO", tIPO_VEHICULO) :
                new ObjectParameter("TIPO_VEHICULO", typeof(string));
    
            var aNIO_FABRICACIONParameter = aNIO_FABRICACION.HasValue ?
                new ObjectParameter("ANIO_FABRICACION", aNIO_FABRICACION) :
                new ObjectParameter("ANIO_FABRICACION", typeof(int));
    
            var nRO_MOTORParameter = nRO_MOTOR != null ?
                new ObjectParameter("NRO_MOTOR", nRO_MOTOR) :
                new ObjectParameter("NRO_MOTOR", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            var uSU_ULT_MODIFICACIONParameter = uSU_ULT_MODIFICACION != null ?
                new ObjectParameter("USU_ULT_MODIFICACION", uSU_ULT_MODIFICACION) :
                new ObjectParameter("USU_ULT_MODIFICACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTUALIZAR_VEHICULO", cOD_VEHICULOParameter, cOD_INFRACTORParameter, cOD_MARCAParameter, cOD_COLORParameter, tIPO_VEHICULOParameter, aNIO_FABRICACIONParameter, nRO_MOTORParameter, eSTADOParameter, fOTOParameter, uSU_ULT_MODIFICACIONParameter);
        }
    
        public virtual ObjectResult<SP_CONSULTAR_INFRACCION_Result> SP_CONSULTAR_INFRACCION(string cOD_INFRACCION)
        {
            var cOD_INFRACCIONParameter = cOD_INFRACCION != null ?
                new ObjectParameter("COD_INFRACCION", cOD_INFRACCION) :
                new ObjectParameter("COD_INFRACCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTAR_INFRACCION_Result>("SP_CONSULTAR_INFRACCION", cOD_INFRACCIONParameter);
        }
    
        public virtual ObjectResult<SP_CONSULTAR_INFRACTOR_Result> SP_CONSULTAR_INFRACTOR(string cOD_INFRACTOR)
        {
            var cOD_INFRACTORParameter = cOD_INFRACTOR != null ?
                new ObjectParameter("COD_INFRACTOR", cOD_INFRACTOR) :
                new ObjectParameter("COD_INFRACTOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTAR_INFRACTOR_Result>("SP_CONSULTAR_INFRACTOR", cOD_INFRACTORParameter);
        }
    
        public virtual int SP_CONSULTAR_PAPELETA(string cOD_PAPELETA)
        {
            var cOD_PAPELETAParameter = cOD_PAPELETA != null ?
                new ObjectParameter("COD_PAPELETA", cOD_PAPELETA) :
                new ObjectParameter("COD_PAPELETA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CONSULTAR_PAPELETA", cOD_PAPELETAParameter);
        }
    
        public virtual ObjectResult<SP_CONSULTAR_POLICIA_Result> SP_CONSULTAR_POLICIA(string cOD_POLICIA)
        {
            var cOD_POLICIAParameter = cOD_POLICIA != null ?
                new ObjectParameter("COD_POLICIA", cOD_POLICIA) :
                new ObjectParameter("COD_POLICIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTAR_POLICIA_Result>("SP_CONSULTAR_POLICIA", cOD_POLICIAParameter);
        }
    
        public virtual ObjectResult<SP_CONSULTAR_USUARIO_Result> SP_CONSULTAR_USUARIO(string login_Usuario)
        {
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTAR_USUARIO_Result>("SP_CONSULTAR_USUARIO", login_UsuarioParameter);
        }
    
        public virtual int SP_CONSULTAR_VEHICULO(string cOD_VEHICULO)
        {
            var cOD_VEHICULOParameter = cOD_VEHICULO != null ?
                new ObjectParameter("COD_VEHICULO", cOD_VEHICULO) :
                new ObjectParameter("COD_VEHICULO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CONSULTAR_VEHICULO", cOD_VEHICULOParameter);
        }
    
        public virtual int SP_ELIMINAR_INFRACCION(string cOD_INFRACCION, string uSU_ULT_MODIFICACION)
        {
            var cOD_INFRACCIONParameter = cOD_INFRACCION != null ?
                new ObjectParameter("COD_INFRACCION", cOD_INFRACCION) :
                new ObjectParameter("COD_INFRACCION", typeof(string));
    
            var uSU_ULT_MODIFICACIONParameter = uSU_ULT_MODIFICACION != null ?
                new ObjectParameter("USU_ULT_MODIFICACION", uSU_ULT_MODIFICACION) :
                new ObjectParameter("USU_ULT_MODIFICACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_INFRACCION", cOD_INFRACCIONParameter, uSU_ULT_MODIFICACIONParameter);
        }
    
        public virtual int SP_ELIMINAR_INFRACTOR(string cOD_INFRACTOR, string uSU_ULT_MODIFICACION)
        {
            var cOD_INFRACTORParameter = cOD_INFRACTOR != null ?
                new ObjectParameter("COD_INFRACTOR", cOD_INFRACTOR) :
                new ObjectParameter("COD_INFRACTOR", typeof(string));
    
            var uSU_ULT_MODIFICACIONParameter = uSU_ULT_MODIFICACION != null ?
                new ObjectParameter("USU_ULT_MODIFICACION", uSU_ULT_MODIFICACION) :
                new ObjectParameter("USU_ULT_MODIFICACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_INFRACTOR", cOD_INFRACTORParameter, uSU_ULT_MODIFICACIONParameter);
        }
    
        public virtual int SP_ELIMINAR_PAPELETA(string cOD_PAPELETA)
        {
            var cOD_PAPELETAParameter = cOD_PAPELETA != null ?
                new ObjectParameter("COD_PAPELETA", cOD_PAPELETA) :
                new ObjectParameter("COD_PAPELETA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_PAPELETA", cOD_PAPELETAParameter);
        }
    
        public virtual int SP_ELIMINAR_POLICIA(string cOD_POLICIA, string uSU_ULT_MODIFICACION)
        {
            var cOD_POLICIAParameter = cOD_POLICIA != null ?
                new ObjectParameter("COD_POLICIA", cOD_POLICIA) :
                new ObjectParameter("COD_POLICIA", typeof(string));
    
            var uSU_ULT_MODIFICACIONParameter = uSU_ULT_MODIFICACION != null ?
                new ObjectParameter("USU_ULT_MODIFICACION", uSU_ULT_MODIFICACION) :
                new ObjectParameter("USU_ULT_MODIFICACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_POLICIA", cOD_POLICIAParameter, uSU_ULT_MODIFICACIONParameter);
        }
    
        public virtual int SP_ELIMINAR_VEHICULO(string cOD_VEHICULO)
        {
            var cOD_VEHICULOParameter = cOD_VEHICULO != null ?
                new ObjectParameter("COD_VEHICULO", cOD_VEHICULO) :
                new ObjectParameter("COD_VEHICULO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR_VEHICULO", cOD_VEHICULOParameter);
        }
    
        public virtual int SP_INSERTAR_INFRACCION(string dESCRIPCION, string cALIFICACION, Nullable<int> pUNTOS, Nullable<decimal> uIT, string eSTADO, string mEDIDA, string uSU_REGISTRO)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var cALIFICACIONParameter = cALIFICACION != null ?
                new ObjectParameter("CALIFICACION", cALIFICACION) :
                new ObjectParameter("CALIFICACION", typeof(string));
    
            var pUNTOSParameter = pUNTOS.HasValue ?
                new ObjectParameter("PUNTOS", pUNTOS) :
                new ObjectParameter("PUNTOS", typeof(int));
    
            var uITParameter = uIT.HasValue ?
                new ObjectParameter("UIT", uIT) :
                new ObjectParameter("UIT", typeof(decimal));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var mEDIDAParameter = mEDIDA != null ?
                new ObjectParameter("MEDIDA", mEDIDA) :
                new ObjectParameter("MEDIDA", typeof(string));
    
            var uSU_REGISTROParameter = uSU_REGISTRO != null ?
                new ObjectParameter("USU_REGISTRO", uSU_REGISTRO) :
                new ObjectParameter("USU_REGISTRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_INFRACCION", dESCRIPCIONParameter, cALIFICACIONParameter, pUNTOSParameter, uITParameter, eSTADOParameter, mEDIDAParameter, uSU_REGISTROParameter);
        }
    
        public virtual int SP_INSERTAR_INFRACTOR(string dNI, string aPE_PATERNO, string aPE_MATERNO, string nOMBRES, string cORREO, string dIRECCION, string cOD_UBIGEO, string sEXO, Nullable<System.DateTime> fEC_NACIMIENTO, byte[] fOTO, string eSTADO, string nRO_BREVETE, string tIPO_BREVETE, string uSU_REGISTRO)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var aPE_PATERNOParameter = aPE_PATERNO != null ?
                new ObjectParameter("APE_PATERNO", aPE_PATERNO) :
                new ObjectParameter("APE_PATERNO", typeof(string));
    
            var aPE_MATERNOParameter = aPE_MATERNO != null ?
                new ObjectParameter("APE_MATERNO", aPE_MATERNO) :
                new ObjectParameter("APE_MATERNO", typeof(string));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var cOD_UBIGEOParameter = cOD_UBIGEO != null ?
                new ObjectParameter("COD_UBIGEO", cOD_UBIGEO) :
                new ObjectParameter("COD_UBIGEO", typeof(string));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var fEC_NACIMIENTOParameter = fEC_NACIMIENTO.HasValue ?
                new ObjectParameter("FEC_NACIMIENTO", fEC_NACIMIENTO) :
                new ObjectParameter("FEC_NACIMIENTO", typeof(System.DateTime));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var nRO_BREVETEParameter = nRO_BREVETE != null ?
                new ObjectParameter("NRO_BREVETE", nRO_BREVETE) :
                new ObjectParameter("NRO_BREVETE", typeof(string));
    
            var tIPO_BREVETEParameter = tIPO_BREVETE != null ?
                new ObjectParameter("TIPO_BREVETE", tIPO_BREVETE) :
                new ObjectParameter("TIPO_BREVETE", typeof(string));
    
            var uSU_REGISTROParameter = uSU_REGISTRO != null ?
                new ObjectParameter("USU_REGISTRO", uSU_REGISTRO) :
                new ObjectParameter("USU_REGISTRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_INFRACTOR", dNIParameter, aPE_PATERNOParameter, aPE_MATERNOParameter, nOMBRESParameter, cORREOParameter, dIRECCIONParameter, cOD_UBIGEOParameter, sEXOParameter, fEC_NACIMIENTOParameter, fOTOParameter, eSTADOParameter, nRO_BREVETEParameter, tIPO_BREVETEParameter, uSU_REGISTROParameter);
        }
    
        public virtual int SP_INSERTAR_POLICIA(string nOMBRE, string pATERNO, string mATERNO, string dNI, string cOD_UBIGEO, Nullable<int> cOD_RANGO, string sEXO, Nullable<System.DateTime> fECHANACIMIENTO, string eSTADO, byte[] fOTO, string uSU_REGISTRO)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var pATERNOParameter = pATERNO != null ?
                new ObjectParameter("PATERNO", pATERNO) :
                new ObjectParameter("PATERNO", typeof(string));
    
            var mATERNOParameter = mATERNO != null ?
                new ObjectParameter("MATERNO", mATERNO) :
                new ObjectParameter("MATERNO", typeof(string));
    
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var cOD_UBIGEOParameter = cOD_UBIGEO != null ?
                new ObjectParameter("COD_UBIGEO", cOD_UBIGEO) :
                new ObjectParameter("COD_UBIGEO", typeof(string));
    
            var cOD_RANGOParameter = cOD_RANGO.HasValue ?
                new ObjectParameter("COD_RANGO", cOD_RANGO) :
                new ObjectParameter("COD_RANGO", typeof(int));
    
            var sEXOParameter = sEXO != null ?
                new ObjectParameter("SEXO", sEXO) :
                new ObjectParameter("SEXO", typeof(string));
    
            var fECHANACIMIENTOParameter = fECHANACIMIENTO.HasValue ?
                new ObjectParameter("FECHANACIMIENTO", fECHANACIMIENTO) :
                new ObjectParameter("FECHANACIMIENTO", typeof(System.DateTime));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            var uSU_REGISTROParameter = uSU_REGISTRO != null ?
                new ObjectParameter("USU_REGISTRO", uSU_REGISTRO) :
                new ObjectParameter("USU_REGISTRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_POLICIA", nOMBREParameter, pATERNOParameter, mATERNOParameter, dNIParameter, cOD_UBIGEOParameter, cOD_RANGOParameter, sEXOParameter, fECHANACIMIENTOParameter, eSTADOParameter, fOTOParameter, uSU_REGISTROParameter);
        }
    
        public virtual int SP_INSERTAR_VEHICULO(string cOD_INFRACTOR, string cOD_MARCA, string cOD_COLOR, string tIPO_VEHICULO, Nullable<int> aNIO_FABRICACION, string nRO_MOTOR, string eSTADO, byte[] fOTO, string uSU_REGISTRO, string uSU_ULT_MODIFICACION)
        {
            var cOD_INFRACTORParameter = cOD_INFRACTOR != null ?
                new ObjectParameter("COD_INFRACTOR", cOD_INFRACTOR) :
                new ObjectParameter("COD_INFRACTOR", typeof(string));
    
            var cOD_MARCAParameter = cOD_MARCA != null ?
                new ObjectParameter("COD_MARCA", cOD_MARCA) :
                new ObjectParameter("COD_MARCA", typeof(string));
    
            var cOD_COLORParameter = cOD_COLOR != null ?
                new ObjectParameter("COD_COLOR", cOD_COLOR) :
                new ObjectParameter("COD_COLOR", typeof(string));
    
            var tIPO_VEHICULOParameter = tIPO_VEHICULO != null ?
                new ObjectParameter("TIPO_VEHICULO", tIPO_VEHICULO) :
                new ObjectParameter("TIPO_VEHICULO", typeof(string));
    
            var aNIO_FABRICACIONParameter = aNIO_FABRICACION.HasValue ?
                new ObjectParameter("ANIO_FABRICACION", aNIO_FABRICACION) :
                new ObjectParameter("ANIO_FABRICACION", typeof(int));
    
            var nRO_MOTORParameter = nRO_MOTOR != null ?
                new ObjectParameter("NRO_MOTOR", nRO_MOTOR) :
                new ObjectParameter("NRO_MOTOR", typeof(string));
    
            var eSTADOParameter = eSTADO != null ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(string));
    
            var fOTOParameter = fOTO != null ?
                new ObjectParameter("FOTO", fOTO) :
                new ObjectParameter("FOTO", typeof(byte[]));
    
            var uSU_REGISTROParameter = uSU_REGISTRO != null ?
                new ObjectParameter("USU_REGISTRO", uSU_REGISTRO) :
                new ObjectParameter("USU_REGISTRO", typeof(string));
    
            var uSU_ULT_MODIFICACIONParameter = uSU_ULT_MODIFICACION != null ?
                new ObjectParameter("USU_ULT_MODIFICACION", uSU_ULT_MODIFICACION) :
                new ObjectParameter("USU_ULT_MODIFICACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_VEHICULO", cOD_INFRACTORParameter, cOD_MARCAParameter, cOD_COLORParameter, tIPO_VEHICULOParameter, aNIO_FABRICACIONParameter, nRO_MOTORParameter, eSTADOParameter, fOTOParameter, uSU_REGISTROParameter, uSU_ULT_MODIFICACIONParameter);
        }
    
        public virtual ObjectResult<SP_LISTAR_INFRACCION_Result> SP_LISTAR_INFRACCION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_INFRACCION_Result>("SP_LISTAR_INFRACCION");
        }
    
        public virtual ObjectResult<SP_LISTAR_INFRACTOR_Result> SP_LISTAR_INFRACTOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_INFRACTOR_Result>("SP_LISTAR_INFRACTOR");
        }
    
        public virtual int SP_LISTAR_PAPELETA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LISTAR_PAPELETA");
        }
    
        public virtual ObjectResult<SP_LISTAR_POLICIA_Result> SP_LISTAR_POLICIA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_POLICIA_Result>("SP_LISTAR_POLICIA");
        }
    
        public virtual int SP_LISTAR_VEHICULO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LISTAR_VEHICULO");
        }
    
        public virtual ObjectResult<SP_LISTARMULTASINFRACTOR_Result> SP_LISTARMULTASINFRACTOR(string cOD_INFRACTOR, Nullable<System.DateTime> fECINI, Nullable<System.DateTime> fECFIN)
        {
            var cOD_INFRACTORParameter = cOD_INFRACTOR != null ?
                new ObjectParameter("COD_INFRACTOR", cOD_INFRACTOR) :
                new ObjectParameter("COD_INFRACTOR", typeof(string));
    
            var fECINIParameter = fECINI.HasValue ?
                new ObjectParameter("FECINI", fECINI) :
                new ObjectParameter("FECINI", typeof(System.DateTime));
    
            var fECFINParameter = fECFIN.HasValue ?
                new ObjectParameter("FECFIN", fECFIN) :
                new ObjectParameter("FECFIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTARMULTASINFRACTOR_Result>("SP_LISTARMULTASINFRACTOR", cOD_INFRACTORParameter, fECINIParameter, fECFINParameter);
        }
    
        public virtual ObjectResult<SP_OBTENER_UBIGEO_Result> SP_OBTENER_UBIGEO(string cOD_UBIGEO)
        {
            var cOD_UBIGEOParameter = cOD_UBIGEO != null ?
                new ObjectParameter("COD_UBIGEO", cOD_UBIGEO) :
                new ObjectParameter("COD_UBIGEO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OBTENER_UBIGEO_Result>("SP_OBTENER_UBIGEO", cOD_UBIGEOParameter);
        }
    
        public virtual ObjectResult<SP_UBIGEO_DEPARTAMENTOS_Result> SP_UBIGEO_DEPARTAMENTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UBIGEO_DEPARTAMENTOS_Result>("SP_UBIGEO_DEPARTAMENTOS");
        }
    
        public virtual ObjectResult<SP_UBIGEO_DISTRITOSPROVINCIASDEPARTAMENTO_Result> SP_UBIGEO_DISTRITOSPROVINCIASDEPARTAMENTO(string iD_DEPA, string iD_PROV)
        {
            var iD_DEPAParameter = iD_DEPA != null ?
                new ObjectParameter("ID_DEPA", iD_DEPA) :
                new ObjectParameter("ID_DEPA", typeof(string));
    
            var iD_PROVParameter = iD_PROV != null ?
                new ObjectParameter("ID_PROV", iD_PROV) :
                new ObjectParameter("ID_PROV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UBIGEO_DISTRITOSPROVINCIASDEPARTAMENTO_Result>("SP_UBIGEO_DISTRITOSPROVINCIASDEPARTAMENTO", iD_DEPAParameter, iD_PROVParameter);
        }
    
        public virtual ObjectResult<SP_UBIGEO_PROVINCIASDEPARTAMENTO_Result> SP_UBIGEO_PROVINCIASDEPARTAMENTO(string iD_DEPA)
        {
            var iD_DEPAParameter = iD_DEPA != null ?
                new ObjectParameter("ID_DEPA", iD_DEPA) :
                new ObjectParameter("ID_DEPA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UBIGEO_PROVINCIASDEPARTAMENTO_Result>("SP_UBIGEO_PROVINCIASDEPARTAMENTO", iD_DEPAParameter);
        }
    }
}
