//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_INFRACTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_INFRACTOR()
        {
            this.TB_VEHICULO = new HashSet<TB_VEHICULO>();
        }
    
        public string COD_INFRACTOR { get; set; }
        public string DNI { get; set; }
        public string APE_PATERNO { get; set; }
        public string APE_MATERNO { get; set; }
        public string NOMBRES { get; set; }
        public string CORREO { get; set; }
        public string DIRECCION { get; set; }
        public string COD_UBIGEO { get; set; }
        public string SEXO { get; set; }
        public Nullable<System.DateTime> FEC_NACIMIENTO { get; set; }
        public byte[] FOTO { get; set; }
        public string NRO_BREVETE { get; set; }
        public string TIPO_BREVETE { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string USU_REGISTRO { get; set; }
        public Nullable<System.DateTime> FEC_ULT_MODIFICACION { get; set; }
        public string USU_ULT_MODIFICACION { get; set; }
        public string ESTADO { get; set; }
    
        public virtual TB_UBIGEO TB_UBIGEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VEHICULO> TB_VEHICULO { get; set; }
    }
}
