//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_INFRACCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_INFRACCION()
        {
            this.TB_PAPELETA = new HashSet<TB_PAPELETA>();
        }
    
        public string COD_INFRACCION { get; set; }
        public string DESCRIPCION_SANCION { get; set; }
        public string CALIFICACION { get; set; }
        public Nullable<int> PUNTOS { get; set; }
        public Nullable<decimal> UIT { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string USU_REGISTRO { get; set; }
        public Nullable<System.DateTime> FEC_ULT_MODIFICACION { get; set; }
        public string USU_ULT_MODIFICACION { get; set; }
        public string ESTADO { get; set; }
        public string MEDIDA_PREVENTIVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PAPELETA> TB_PAPELETA { get; set; }
    }
}
