//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_INFRACCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_INFRACCION()
        {
            this.TB_PAPELETA = new HashSet<TB_PAPELETA>();
        }
    
        public string COD_INFRACCION { get; set; }
        public string DESCRIPCION_SANCION { get; set; }
        public string CALIFICACION { get; set; }
        public Nullable<int> PUNTOS { get; set; }
        public Nullable<decimal> UIT { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string USU_REGISTRO { get; set; }
        public Nullable<System.DateTime> FEC_ULT_MODIFICACION { get; set; }
        public string USU_ULT_MODIFICACION { get; set; }
        public string ESTADO { get; set; }
        public string MEDIDA_PREVENTIVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PAPELETA> TB_PAPELETA { get; set; }
    }
}
