//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MARCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_MARCA()
        {
            this.TB_VEHICULO = new HashSet<TB_VEHICULO>();
        }
    
        public string COD_MARCA { get; set; }
        public string MARCA { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string USU_REGISTRO { get; set; }
        public Nullable<System.DateTime> FEC_ULT_MODIFICACION { get; set; }
        public string USU_ULT_MODIFICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VEHICULO> TB_VEHICULO { get; set; }
    }
}
