//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PAPELETA
    {
        public string COD_PAPELETA { get; set; }
        public string COD_INFRACCION { get; set; }
        public string COD_POLICIA { get; set; }
        public string COD_VEHICULO { get; set; }
        public System.DateTime FECHA_INFRACCION { get; set; }
        public System.TimeSpan HORA_INFRACCION { get; set; }
        public string LUGAR_INFRACCION { get; set; }
        public string REFERENCIA { get; set; }
        public string INFO_ADICIONAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTADO_PAPELETA { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string USU_REGISTRO { get; set; }
        public Nullable<System.DateTime> FEC_ULT_MODIFICACION { get; set; }
        public string USU_ULT_MODIFICACION { get; set; }
    
        public virtual TB_INFRACCION TB_INFRACCION { get; set; }
        public virtual TB_POLICIA TB_POLICIA { get; set; }
        public virtual TB_VEHICULO TB_VEHICULO { get; set; }
    }
}
