//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PAPELETA
    {
        public string COD_PAPELETA { get; set; }
        public string COD_INFRACCION { get; set; }
        public string COD_POLICIA { get; set; }
        public string COD_VEHICULO { get; set; }
        public System.DateTime FECHA_INFRACCION { get; set; }
        public System.TimeSpan HORA_INFRACCION { get; set; }
        public string LUGAR_INFRACCION { get; set; }
        public string REFERENCIA { get; set; }
        public string INFO_ADICIONAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTADO_PAPELETA { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string USU_REGISTRO { get; set; }
        public Nullable<System.DateTime> FEC_ULT_MODIFICACION { get; set; }
        public string USU_ULT_MODIFICACION { get; set; }
    
        public virtual TB_INFRACCION TB_INFRACCION { get; set; }
        public virtual TB_POLICIA TB_POLICIA { get; set; }
        public virtual TB_VEHICULO TB_VEHICULO { get; set; }
        public string DESCRIPCION { get; internal set; }
    }
}
