//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_POLICIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_POLICIA()
        {
            this.TB_PAPELETA = new HashSet<TB_PAPELETA>();
        }
    
        public string COD_POLICIA { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string DNI { get; set; }
        public string COD_UBIGEO { get; set; }
        public string SEXO { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string ESTADO { get; set; }
        public byte[] FOTO { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string USU_REGISTRO { get; set; }
        public Nullable<System.DateTime> FEC_ULT_MODIFICACION { get; set; }
        public string USU_ULT_MODIFICACION { get; set; }
        public Nullable<int> COD_RANGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PAPELETA> TB_PAPELETA { get; set; }
        public virtual TB_UBIGEO TB_UBIGEO { get; set; }
        public virtual TB_RANGO TB_RANGO { get; set; }
    }
}
