//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RANGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_RANGO()
        {
            this.TB_POLICIA = new HashSet<TB_POLICIA>();
        }
    
        public int COD_RANGO { get; set; }
        public string NOM_RANGO { get; set; }
        public string DESCRIPCION_RANGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_POLICIA> TB_POLICIA { get; set; }
    }
}
