//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_UBIGEO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_UBIGEO()
        {
            this.TB_INFRACTOR = new HashSet<TB_INFRACTOR>();
            this.TB_POLICIA = new HashSet<TB_POLICIA>();
        }
    
        public string COD_UBIGEO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string USU_REGISTRO { get; set; }
        public Nullable<System.DateTime> FEC_ULT_MODIFICACION { get; set; }
        public string USU_ULT_MODIFICACION { get; set; }
        public string ID_DEPA { get; set; }
        public string ID_PROV { get; set; }
        public string ID_DIST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_INFRACTOR> TB_INFRACTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_POLICIA> TB_POLICIA { get; set; }
    }
}
