//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_VEHICULO()
        {
            this.TB_PAPELETA = new HashSet<TB_PAPELETA>();
        }
    
        public string COD_VEHICULO { get; set; }
        public string COD_INFRACTOR { get; set; }
        public string COD_MARCA { get; set; }
        public string COD_COLOR { get; set; }
        public Nullable<int> ANIO_FABRICACION { get; set; }
        public string NRO_MOTOR { get; set; }
        public string ESTADO { get; set; }
        public byte[] FOTO { get; set; }
        public Nullable<System.DateTime> FEC_REGISTRO { get; set; }
        public string USU_REGISTRO { get; set; }
        public Nullable<System.DateTime> FEC_ULT_MODIFICACION { get; set; }
        public string USU_ULT_MODIFICACION { get; set; }
        public Nullable<int> COD_TIPO_VEHICULO { get; set; }
    
        public virtual TB_COLOR TB_COLOR { get; set; }
        public virtual TB_INFRACTOR TB_INFRACTOR { get; set; }
        public virtual TB_MARCA TB_MARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PAPELETA> TB_PAPELETA { get; set; }
        public virtual TB_TIPO_VEHICULO TB_TIPO_VEHICULO { get; set; }
    }
}
