//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_INFRACTOR
    {
        public string COD_INFRACTOR { get; set; }
        public string DNI { get; set; }
        public string NOMBRES { get; set; }
        public string APE_PATERNO { get; set; }
        public string APE_MATERNO { get; set; }
        public string CORREO { get; set; }
        public string DIRECCION { get; set; }
        public string SEXO { get; set; }
        public Nullable<System.DateTime> FEC_NACIMIENTO { get; set; }
        public string NRO_BREVETE { get; set; }
        public string TIPO_BREVETE { get; set; }
        public string COD_UBIGEO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
        public byte[] FOTO { get; set; }
        public string ESTADO { get; set; }
    }
}
