//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PAPELETA
    {
        public string COD_PAPELETA { get; set; }
        public string COD_INFRACCION { get; set; }
        public string DESCRIPCION_SANCION { get; set; }
        public string POLICIA { get; set; }
        public string COD_VEHICULO { get; set; }
        public System.DateTime FECHA_INFRACCION { get; set; }
        public System.TimeSpan HORA_INFRACCION { get; set; }
        public string LUGAR_INFRACCION { get; set; }
        public string DESCRIPCION { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTADO_PAPELETA { get; set; }
    }
}
