//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_POLICIA
    {
        public string COD_POLICIA { get; set; }
        public string PATERNO { get; set; }
        public string MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string DNI { get; set; }
        public Nullable<int> COD_RANGO { get; set; }
        public string SEXO { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string ESTADO { get; set; }
        public byte[] FOTO { get; set; }
        public string RANGO { get; set; }
        public string COD_UBIGEO { get; set; }
        public string DISTRITO { get; set; }
        public string PROVINCIA { get; set; }
        public string DEPARTAMENTO { get; set; }
    }
}
