//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_UBIGEO
    {
        public string COD_UBIGEO { get; set; }
        public string ID_DEPA { get; set; }
        public string ID_PROV { get; set; }
        public string ID_DIST { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string PROVINCIA { get; set; }
        public string DISTRITO { get; set; }
    }
}
