//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VEHICULO
    {
        public string COD_VEHICULO { get; set; }
        public string DNI { get; set; }
        public string INFRACTOR { get; set; }
        public string MARCA { get; set; }
        public string COLOR { get; set; }
        public string TIPO_VEHICULO { get; set; }
        public Nullable<int> ANIO_FABRICACION { get; set; }
        public string NRO_MOTOR { get; set; }
        public string ESTADO { get; set; }
    }
}
