//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VISTAMULTAS
    {
        public string COD_PAPELETA { get; set; }
        public string COD_INFRACTOR { get; set; }
        public string INFRACTOR { get; set; }
        public string LUGAR_INFRACCION { get; set; }
        public string FALTA_COMETIDA { get; set; }
        public string CALIFICACION { get; set; }
        public Nullable<decimal> UIT { get; set; }
        public System.DateTime FECHA_INFRACCION { get; set; }
        public string POLICIA { get; set; }
        public string ESTADO_PAPELETA { get; set; }
    }
}
