//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeletaWeb_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VEHICULO
    {
        public string COD_VEHICULO { get; set; }
        public string DNI { get; set; }
        public string INFRACTOR { get; set; }
        public string MARCA { get; set; }
        public string COLOR { get; set; }
        public string TIPO_VEHICULO { get; set; }
        public Nullable<int> ANIO_FABRICACION { get; set; }
        public string NRO_MOTOR { get; set; }
        public string ESTADO { get; set; }
    }
}
